export type Lang = 'ru' | 'en' | 'tr';
export const LANGS: [Lang,string][] = [['ru','Русский'],['en','English'],['tr','Türkçe']];
let current: Lang = 'ru';

const RU: Record<string,string> = {
 title:'ПОСЛЕДНИЙ КУРЬЕР',subtitle:'НОВОГРАД / ПОСЛЕДНИЙ МАРШРУТ',start:'НАЧАТЬ СМЕНУ',garage:'ГАРАЖ',progress:'ПРОГРЕСС',settings:'НАСТРОЙКИ',language:'ЯЗЫК',sound:'ЗВУК',on:'ВКЛ',off:'ВЫКЛ',back:'НАЗАД',controls:'WASD / стрелки — движение • SHIFT — ускорение • E — заказ • M — карта • G — гараж',day:'ДЕНЬ',money:'ДЕНЬГИ',rep:'РЕПУТАЦИЯ',deliveries:'Доставки',best:'Рекорд',selected:'ВЫБРАНО',select:'ВЫБРАТЬ',buy:'КУПИТЬ',notEnough:'Недостаточно денег',upgrade:'УЛУЧШЕНИЯ',max:'МАКС',speed:'СКОРОСТЬ',garageHint:'Транспорт и оборудование определяют твой стиль доставки.',accept:'Заказ принят',deliver:'Доставка',shiftComplete:'Смена началась. Город живёт своей жизнью.',saved:'Сохранено',districtCenter:'ЦЕНТР',districtOld:'СТАРЫЙ ГОРОД',districtIndustrial:'ПРОМЗОНА',districtResidential:'ЖИЛОЙ РАЙОН',districtPort:'ПОРТ',districtSuburbs:'ПРИГОРОД',cargoMedicine:'ЛЕКАРСТВА',cargoDocuments:'ДОКУМЕНТЫ',cargoFood:'ЕДА',cargoPackage:'ПОСЫЛКА',cargoParts:'ДЕТАЛИ',cargoBlood:'КРОВЬ',missionStandard:'ОБЫЧНЫЙ ЗАКАЗ',missionTimed:'СРОЧНЫЙ ЗАКАЗ',missionFragile:'ХРУПКИЙ ГРУЗ',missionMulti:'МАРШРУТ',missionHighrisk:'ОПАСНЫЙ ЗАКАЗ',achFirst:'Первая доставка',achTen:'10 доставок',achStreak:'Серия x5',achRich:'10 000 ₽',achRep:'50 репутации',achFleet:'Весь транспорт',achStory:'Продвинутый сюжет',achNight:'Ночной курьер'
};
const EN: Record<string,string> = {
 title:'THE LAST COURIER',subtitle:'NOVOGRAD / LAST ROUTE',start:'START SHIFT',garage:'GARAGE',progress:'PROGRESS',settings:'SETTINGS',language:'LANGUAGE',sound:'SOUND',on:'ON',off:'OFF',back:'BACK',controls:'WASD / arrows — drive • SHIFT — boost • E — order • M — map • G — garage',day:'DAY',money:'MONEY',rep:'REP',deliveries:'Deliveries',best:'Best',selected:'SELECTED',select:'SELECT',buy:'BUY',notEnough:'Not enough money',upgrade:'UPGRADES',max:'MAX',speed:'SPEED',garageHint:'Your vehicle and equipment define your delivery style.',accept:'Order accepted',deliver:'Delivery',shiftComplete:'Shift started. The city has a life of its own.',saved:'Saved',districtCenter:'CENTER',districtOld:'OLD TOWN',districtIndustrial:'INDUSTRIAL',districtResidential:'RESIDENTIAL',districtPort:'PORT',districtSuburbs:'SUBURBS',cargoMedicine:'MEDICINE',cargoDocuments:'DOCUMENTS',cargoFood:'FOOD',cargoPackage:'PACKAGE',cargoParts:'PARTS',cargoBlood:'BLOOD',missionStandard:'STANDARD ORDER',missionTimed:'TIMED ORDER',missionFragile:'FRAGILE CARGO',missionMulti:'MULTI-STOP ROUTE',missionHighrisk:'HIGH-RISK ORDER',achFirst:'First delivery',achTen:'10 deliveries',achStreak:'5x streak',achRich:'10,000 ₽',achRep:'50 reputation',achFleet:'Full fleet',achStory:'Story progress',achNight:'Night courier'
};
const TR: Record<string,string> = {
 title:'SON KURYE',subtitle:'NOVOGRAD / SON ROTA',start:'VARDİYAYA BAŞLA',garage:'GARAJ',progress:'İLERLEME',settings:'AYARLAR',language:'DİL',sound:'SES',on:'AÇIK',off:'KAPALI',back:'GERİ',controls:'WASD / oklar — sürüş • SHIFT — hız • E — sipariş • M — harita • G — garaj',day:'GÜN',money:'PARA',rep:'İTİBAR',deliveries:'Teslimatlar',best:'Rekor',selected:'SEÇİLDİ',select:'SEÇ',buy:'SATIN AL',notEnough:'Yetersiz para',upgrade:'GELİŞTİRMELER',max:'MAKS',speed:'HIZ',garageHint:'Araç ve ekipmanın teslimat tarzını belirler.',accept:'Sipariş kabul edildi',deliver:'Teslimat',shiftComplete:'Vardiya başladı. Şehir kendi hayatını yaşıyor.',saved:'Kaydedildi',districtCenter:'MERKEZ',districtOld:'ESKİ ŞEHİR',districtIndustrial:'SANAYİ',districtResidential:'KONUT',districtPort:'LİMAN',districtSuburbs:'VAROŞLAR',cargoMedicine:'İLAÇ',cargoDocuments:'BELGELER',cargoFood:'YEMEK',cargoPackage:'PAKET',cargoParts:'PARÇALAR',cargoBlood:'KAN',missionStandard:'STANDART SİPARİŞ',missionTimed:'SÜRELİ SİPARİŞ',missionFragile:'KIRILABİLİR YÜK',missionMulti:'ÇOK DURAKLI ROTA',missionHighrisk:'YÜKSEK RİSKLİ SİPARİŞ',achFirst:'İlk teslimat',achTen:'10 teslimat',achStreak:'5x seri',achRich:'10.000 ₽',achRep:'50 itibar',achFleet:'Tam filo',achStory:'Hikâye ilerlemesi',achNight:'Gece kuryesi'
};
const dict: Record<Lang,Record<string,string>> = {ru:RU,en:EN,tr:TR};
export function getLang(): Lang { return current; }
export function setLang(lang:string){ current = (lang==='en'||lang==='tr') ? lang : 'ru'; }
export function detectLang(ysdk:any): Lang { const raw=ysdk?.environment?.i18n?.lang || (typeof navigator!=='undefined'?navigator.language:'ru'); const l=String(raw).toLowerCase().split('-')[0]; return l==='en'||l==='tr' ? l : 'ru'; }
export function t(key:string): string { return dict[current][key] ?? RU[key] ?? key; }
