import Phaser from 'phaser';
import './style.css';
import {detectLang,getLang,setLang,LANGS,t} from './i18n';

type VehicleId='bike'|'scooter'|'moto'|'car'|'van';
type Weather='clear'|'rain'|'fog'|'storm';
type Kind='standard'|'timed'|'fragile'|'multi'|'highrisk';
type Save={money:number;rep:number;day:number;deliveries:number;streak:number;best:number;vehicle:VehicleId;upgrades:Record<string,number>;unlocked:VehicleId[];story:number;achievements:string[];adBoost:number;lang:string};
const KEY='last-courier-save-v6';
const DEFAULT:Save={money:350,rep:0,day:1,deliveries:0,streak:0,best:0,vehicle:'bike',upgrades:{engine:0,brakes:0,battery:0,bag:0,nav:0},unlocked:['bike'],story:0,achievements:[],adBoost:0,lang:'auto'};
const clone=():Save=>JSON.parse(JSON.stringify(DEFAULT));
function load():Save{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?{...clone(),...x,upgrades:{...DEFAULT.upgrades,...(x.upgrades||{})}}:clone()}catch{return clone()}}
let save=load();
function persist(s=save){localStorage.setItem(KEY,JSON.stringify(s))}
function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n))}
function dist(a:{x:number;y:number},b:{x:number;y:number}){return Math.hypot(a.x-b.x,a.y-b.y)}

class Platform{
 ysdk:any;player:any;ready=false;pauseHandler?:()=>void;resumeHandler?:()=>void;
 async init(){try{const Y=(window as any).YaGames;if(!Y){setLang('ru');return}this.ysdk=await Y.init();this.ready=true;const detected=detectLang(this.ysdk);if(save.lang==='auto')save.lang=detected;setLang(save.lang);this.ysdk?.features?.LoadingAPI?.ready?.();this.pauseHandler=()=>window.dispatchEvent(new Event('lc-ad-open'));this.resumeHandler=()=>window.dispatchEvent(new Event('lc-ad-close'));this.ysdk.on?.('game_api_pause',this.pauseHandler);this.ysdk.on?.('game_api_resume',this.resumeHandler);this.player=await this.ysdk.getPlayer?.({scopes:false});const cloud=await this.player?.getData?.();if(cloud?.money!==undefined){save={...clone(),...cloud,upgrades:{...DEFAULT.upgrades,...(cloud.upgrades||{})}};setLang(save.lang||detected);persist(save)}}catch{setLang(save.lang==='en'||save.lang==='tr'?save.lang:'ru')}}
 async cloud(){persist();try{await this.player?.setData?.(save,true)}catch{}}
 persist(){persist();void this.cloud()}
 gameplay(on:boolean){try{const api=this.ysdk?.features?.GameplayAPI;if(on)api?.start?.();else api?.stop?.()}catch{}}
 adFull(){this.gameplay(false);try{this.ysdk?.adv?.showFullscreenAdv?.({callbacks:{onOpen:()=>window.dispatchEvent(new Event('lc-ad-open')),onClose:()=>window.dispatchEvent(new Event('lc-ad-close')),onError:()=>window.dispatchEvent(new Event('lc-ad-close'))}})}catch{this.gameplay(true)}}
 reward(onReward:()=>void){this.gameplay(false);try{this.ysdk?.adv?.showRewardedVideo?.({callbacks:{onOpen:()=>window.dispatchEvent(new Event('lc-ad-open')),onRewarded:onReward,onClose:()=>{window.dispatchEvent(new Event('lc-ad-close'));this.gameplay(true)},onError:()=>{window.dispatchEvent(new Event('lc-ad-close'));this.gameplay(true)}}})}catch{this.gameplay(true)}}
 score(){try{if(this.ysdk?.leaderboards?.setScore)this.ysdk.leaderboards.setScore('last_courier_deliveries',save.deliveries)}catch{}}
}
const platform=new Platform();

const VEH:{id:VehicleId;name:string;price:number;speed:number;turn:number;cap:number}[]=[
{id:'bike',name:'Велосипед',price:0,speed:190,turn:1.25,cap:1},{id:'scooter',name:'Скутер',price:900,speed:235,turn:1.1,cap:2},{id:'moto',name:'Мотоцикл',price:2400,speed:285,turn:.98,cap:3},{id:'car',name:'Автомобиль',price:6200,speed:255,turn:.78,cap:5},{id:'van',name:'Фургон',price:11500,speed:220,turn:.62,cap:8}];
const UP={engine:{name:'Двигатель',base:450,max:5},brakes:{name:'Тормоза',base:380,max:5},battery:{name:'Батарея',base:420,max:5},bag:{name:'Сумка',base:500,max:5},nav:{name:'Навигация',base:600,max:5}};
const D=[
{name:'districtCenter',x:900,y:430,c:0x17384b,pay:1.3,risk:1.2},{name:'districtOld',x:370,y:320,c:0x392b43,pay:1.15,risk:1.1},{name:'districtIndustrial',x:1390,y:850,c:0x493923,pay:1.5,risk:1.55},{name:'districtResidential',x:360,y:820,c:0x214438,pay:1,risk:.8},{name:'districtPort',x:1510,y:270,c:0x23444d,pay:1.75,risk:1.7},{name:'districtSuburbs',x:930,y:1050,c:0x30422e,pay:1.35,risk:.7}];
const CARGO=['cargoMedicine','cargoDocuments','cargoFood','cargoPackage','cargoParts','cargoBlood'];
const KINDS:Kind[]=['standard','timed','fragile','multi','highrisk'];
function v(){return VEH.find(x=>x.id===save.vehicle)!}
function upCost(k:string){const u=(UP as any)[k];return Math.round(u.base*Math.pow(1.62,save.upgrades[k]||0))}
function missionName(k:Kind){return t(({standard:'missionStandard',timed:'missionTimed',fragile:'missionFragile',multi:'missionMulti',highrisk:'missionHighrisk'} as any)[k])}

class Boot extends Phaser.Scene{constructor(){super('Boot')}create(){this.cameras.main.setBackgroundColor('#061017');const w=this.scale.width,h=this.scale.height;this.add.text(w/2,h/2-38,t('title'),{fontFamily:'Arial Black',fontSize:42,color:'#eaf8ff'}).setOrigin(.5);this.add.text(w/2,h/2+18,t('subtitle'),{fontSize:14,color:'#71a0b5',letterSpacing:3}).setOrigin(.5);this.add.text(w/2,h/2+58,'Loading…',{fontSize:13,color:'#7fe1ff'}).setOrigin(.5);platform.init().finally(()=>this.time.delayedCall(450,()=>this.scene.start('Menu')))}}

class Menu extends Phaser.Scene{
 create(){this.cameras.main.setBackgroundColor('#061017');const w=this.scale.width,h=this.scale.height;const g=this.add.graphics();g.fillGradientStyle(0x061017,0x061017,0x0c2635,0x061017,1);g.fillRect(0,0,w,h);for(let i=0;i<30;i++){g.fillStyle(0x49cfff,Math.random()*.16);g.fillCircle(Math.random()*w,Math.random()*h,1+Math.random()*2)}this.add.circle(w*.76,h*.45,210,0x0b526d,.22);this.add.circle(w*.76,h*.45,130,0x18a7d0,.12);
 this.add.text(w*.08,h*.13,t('title'),{fontFamily:'Arial Black',fontSize:Math.min(66,w*.07),color:'#ecf9ff'});this.add.text(w*.08,h*.25,t('subtitle'),{fontSize:16,color:'#6e9caf',letterSpacing:3});this.add.text(w*.08,h*.35,'23:47  •  NOVOGRAD',{fontSize:22,color:'#9ed9ed'});this.add.text(w*.08,h*.41,'A living city. One courier. No second chances.',{fontSize:15,color:'#688493'});
 this.button(w*.08,h*.54,t('start'),()=>this.scene.start('City'));this.button(w*.08,h*.65,t('garage'),()=>this.scene.start('Garage'));this.button(w*.08,h*.76,t('progress'),()=>this.progress());this.button(w*.08,h*.87,'⚙ '+t('settings'),()=>this.scene.start('Settings'));
 const ad=this.add.text(w*.58,h*.87,'🎁  +25%',{fontSize:14,color:'#ffd36b',backgroundColor:'#132936',padding:{left:12,right:12,top:9,bottom:9}}).setInteractive();ad.on('pointerdown',()=>platform.reward(()=>{save.adBoost=1;platform.persist();ad.setText('✓ '+t('saved'))}));
 this.add.text(w*.92,h*.12,`${t('day')} ${save.day}\n${save.money} ₽\nREP ${save.rep}`,{fontSize:15,color:'#9fb7c2',align:'right',lineSpacing:7}).setOrigin(1,0);this.add.text(w*.92,h*.88,t('controls'),{fontSize:11,color:'#4e6d7b',align:'right',wordWrap:{width:w*.45}}).setOrigin(1,1)}
 button(x:number,y:number,label:string,fn:()=>void){const b=this.add.text(x,y,label,{fontSize:18,color:'#dff7ff',backgroundColor:'#102733',padding:{left:22,right:22,top:12,bottom:12}}).setInteractive({useHandCursor:true});b.on('pointerdown',fn);b.on('pointerover',()=>b.setColor('#5de0ff'));b.on('pointerout',()=>b.setColor('#dff7ff'));return b}
 progress(){const a=save.achievements.map(id=>t(({first:'achFirst',ten:'achTen',streak:'achStreak',rich:'achRich',rep:'achRep',fleet:'achFleet',story:'achStory',night:'achNight'} as any)[id]||id));this.add.text(this.scale.width*.7,this.scale.height*.42,`${t('progress')}\n\n${t('deliveries')}: ${save.deliveries}\n${t('best')}: ${save.best}\n${t('rep')}: ${save.rep}\n${t('money')}: ${save.money} ₽\n\n${a.join('\n')||'—'}\n\n${t('back')}: ESC`,{fontSize:16,color:'#d8edf4',backgroundColor:'#0b1d27',padding:24,lineSpacing:6}).setOrigin(.5)}
}

class Settings extends Phaser.Scene{
 create(){this.cameras.main.setBackgroundColor('#07131b');this.add.text(55,45,t('settings'),{fontFamily:'Arial Black',fontSize:32,color:'#e7f7ff'});this.add.text(55,105,t('language'),{fontSize:16,color:'#87a4b2'});LANGS.forEach(([id,name],i)=>{const b=this.add.text(55+i*180,145,name,{fontSize:16,color:getLang()===id?'#5de0ff':'#d7e7ee',backgroundColor:'#102631',padding:{left:15,right:15,top:10,bottom:10}}).setInteractive();b.on('pointerdown',()=>{save.lang=id;setLang(id);platform.persist();this.scene.restart()})});this.add.text(55,235,t('sound'),{fontSize:16,color:'#87a4b2'});const sound=this.add.text(55,275,'🔊  '+t('on'),{fontSize:16,color:'#d7e7ee',backgroundColor:'#102631',padding:{left:15,right:15,top:10,bottom:10}}).setInteractive();sound.on('pointerdown',()=>sound.setText(sound.text.includes(t('on'))?'🔇  '+t('off'):'🔊  '+t('on')));this.add.text(55,360,'ESC  '+t('back'),{fontSize:14,color:'#658391'});this.input.keyboard?.once('keydown-ESC',()=>this.scene.start('Menu'))}
}

class Garage extends Phaser.Scene{
 create(){this.cameras.main.setBackgroundColor('#07131b');this.add.text(35,30,t('garage'),{fontFamily:'Arial Black',fontSize:31,color:'#eaf7ff'});this.add.text(35,70,t('garageHint'),{fontSize:14,color:'#6e8c9b'});this.add.text(this.scale.width-35,34,`${save.money} ₽`,{fontSize:22,color:'#ffd36b'}).setOrigin(1,0);const w=this.scale.width;
 VEH.forEach((x,i)=>{const col=i%3,row=Math.floor(i/3),px=50+col*w*.31,py=125+row*145,ok=save.unlocked.includes(x.id),sel=save.vehicle===x.id;this.add.rectangle(px+110,py+58,220,112,sel?0x123f50:0x0e222d,.95).setStrokeStyle(sel?2:1,sel?0x55dcff:0x29424d);this.add.text(px+18,py+15,x.name,{fontSize:17,color:'#e4f4fa'});this.add.text(px+18,py+45,`${t('speed')}: ${x.speed}\nCAP: ${x.cap}`,{fontSize:12,color:'#89a8b6',lineSpacing:4});const b=this.add.text(px+18,py+88,ok?(sel?'✓ '+t('selected'):t('select')):`${t('buy')} ${x.price} ₽`,{fontSize:12,color:ok?'#5ce0ff':'#ffd36b',backgroundColor:'#0a1820',padding:{left:8,right:8,top:6,bottom:6}}).setInteractive();b.on('pointerdown',()=>{if(ok){save.vehicle=x.id;platform.persist();this.scene.restart()}else if(save.money>=x.price){save.money-=x.price;save.unlocked.push(x.id);save.vehicle=x.id;platform.persist();this.scene.restart()}else{this.add.text(px+18,py+118,t('notEnough'),{fontSize:10,color:'#ff8b8b'})}})});
 this.add.text(35,420,t('upgrade'),{fontFamily:'Arial Black',fontSize:22,color:'#d9edf4'});Object.entries(UP).forEach(([key,u],i)=>{const x=35+(i%3)*w*.31,y=465+Math.floor(i/3)*90,l=save.upgrades[key]||0,max=l>=u.max;this.add.text(x,y,`${u.name}  ${l}/${u.max}`,{fontSize:15,color:'#b7d1dc'});this.add.text(x,y+25,'●'.repeat(l)+'○'.repeat(u.max-l),{fontSize:12,color:'#58d7f5'});const b=this.add.text(x+145,y+4,max?t('max'):`+1  ${upCost(key)} ₽`,{fontSize:12,color:max?'#6bdc99':'#ffd36b',backgroundColor:'#10232d',padding:{left:8,right:8,top:6,bottom:6}}).setInteractive();b.on('pointerdown',()=>{const c=upCost(key);if(!max&&save.money>=c){save.money-=c;save.upgrades[key]=l+1;platform.persist();this.scene.restart()}})});this.add.text(35,this.scale.height-30,'ESC  '+t('back'),{fontSize:14,color:'#658391'});this.input.keyboard?.once('keydown-ESC',()=>this.scene.start('Menu'))}
}

interface Job{x:number;y:number;from:number;to:number;reward:number;deadline:number;kind:Kind;cargo:string;step:number;active:boolean;multiTo?:number}
class City extends Phaser.Scene{
 p!:Phaser.GameObjects.Container;jobs:Job[]=[];traffic:{o:Phaser.GameObjects.Rectangle;vx:number;vy:number}[]=[];hud!:Phaser.GameObjects.Text;panel!:Phaser.GameObjects.Text;toast!:Phaser.GameObjects.Text;mini!:Phaser.GameObjects.Graphics;overlay!:Phaser.GameObjects.Rectangle;weather:Weather='clear';weatherT=40;eventT=28;clock=0;energy=100;current?:Job;map=false;rain:number[][]=[];adLock=false;keys:any={};cursor!:Phaser.Types.Input.Keyboard.CursorKeys;
 create(){this.cameras.main.setBounds(0,0,1800,1200);this.makeWorld();this.makePlayer();this.makeJobs();this.makeTraffic();this.makeUI();this.bind();this.changeWeather('clear');this.newToast(t('shiftComplete'));platform.gameplay(true);window.addEventListener('lc-ad-open',this.pauseForAd);window.addEventListener('lc-ad-close',this.resumeAfterAd)}
 shutdown(){platform.gameplay(false);window.removeEventListener('lc-ad-open',this.pauseForAd);window.removeEventListener('lc-ad-close',this.resumeAfterAd)}
 pauseForAd=()=>{this.adLock=true;this.scene.pause()};resumeAfterAd=()=>{this.adLock=false;this.scene.resume()};
 bind(){const kb=this.input.keyboard!;this.cursor=kb.createCursorKeys();this.keys.w=kb.addKey(Phaser.Input.Keyboard.KeyCodes.W);this.keys.a=kb.addKey(Phaser.Input.Keyboard.KeyCodes.A);this.keys.s=kb.addKey(Phaser.Input.Keyboard.KeyCodes.S);this.keys.d=kb.addKey(Phaser.Input.Keyboard.KeyCodes.D);this.keys.shift=kb.addKey(Phaser.Input.Keyboard.KeyCodes.SHIFT);kb.on('keydown-E',()=>this.interact());kb.on('keydown-M',()=>this.toggleMap());kb.on('keydown-G',()=>this.scene.start('Garage'));kb.on('keydown-ESC',()=>this.scene.start('Menu'));window.addEventListener('blur',this.pauseFocus);window.addEventListener('focus',this.resumeFocus)}
 pauseFocus=()=>{if(!this.adLock){platform.gameplay(false);this.scene.pause()}};resumeFocus=()=>{if(!this.adLock){this.scene.resume();platform.gameplay(true)}};
 makeWorld(){const g=this.add.graphics();g.fillStyle(0x07131b);g.fillRect(0,0,1800,1200);D.forEach(d=>{g.fillStyle(d.c,.7);g.fillRect(d.x-300,d.y-210,600,420)});for(let x=20;x<1800;x+=150){g.fillStyle(0x14252e);g.fillRect(x,0,64,1200);g.lineStyle(2,0x4a646d,.38);for(let y=10;y<1200;y+=48)g.lineBetween(x+31,y,x+31,y+22)}for(let y=45;y<1200;y+=170){g.fillStyle(0x162830);g.fillRect(0,y,1800,72);g.lineStyle(2,0x526970,.35);for(let x=10;x<1800;x+=52)g.lineBetween(x,y+36,x+25,y+36)}for(let i=0;i<170;i++){const x=Math.floor(Math.random()*59)*30+8,y=Math.floor(Math.random()*39)*30+8;if((x%150<64)&&(y%170<72))continue;g.fillStyle(0x20323b,.95);g.fillRect(x,y,20+Math.random()*32,16+Math.random()*26);if(Math.random()>.35){g.fillStyle(0x77d9e5,.14);g.fillRect(x+5,y+5,3,3)}}D.forEach(d=>{g.lineStyle(2,0x65e2ff,.22);g.strokeCircle(d.x,d.y,92);this.add.text(d.x,d.y-112,t(d.name),{fontSize:11,color:'#8bb6c4',backgroundColor:'#07141b',padding:4}).setOrigin(.5)});this.add.text(900,600,'NOVOGRAD',{fontFamily:'Arial Black',fontSize:54,color:'#7ad8ff',alpha:.035}).setOrigin(.5)}
 makePlayer(){this.p=this.add.container(900,600);this.p.setDepth(20);this.p.add(this.add.ellipse(0,10,32,13,0x000000,.35));this.p.add(this.add.rectangle(0,0,23,38,0x43d8ff).setStrokeStyle(2,0xc9f9ff));this.p.add(this.add.triangle(0,-23,0,-8,8,5,-8,5,0xefffff));this.p.add(this.add.circle(0,-8,4,0xefffff));this.cameras.main.startFollow(this.p,true,.08,.08)}
 makeJobs(){this.jobs=[];for(let i=0;i<10;i++)this.spawnJob(i)}
 spawnJob(i:number){const from=Math.floor(Math.random()*D.length),to0=Math.floor(Math.random()*D.length),to=to0===from?(to0+1)%D.length:to0,a=D[from],b=D[to];const kind=KINDS[Math.floor(Math.random()*KINDS.length)];const mult=1+(kind==='timed'?.35:kind==='fragile'?.28:kind==='multi'?.55:kind==='highrisk'?.9:0);this.jobs[i]={x:a.x+(Math.random()-.5)*160,y:a.y+(Math.random()-.5)*130,from,to,reward:Math.round((240+Math.random()*320)*a.pay*mult),deadline:kind==='timed'?35+Math.random()*25:75+Math.random()*45,kind,cargo:CARGO[Math.floor(Math.random()*CARGO.length)],step:0,active:false,multiTo:kind==='multi'?Math.floor(Math.random()*D.length):undefined};void b}
 makeTraffic(){for(let i=0;i<34;i++){const horizontal=Math.random()>.5;const o=this.add.rectangle(Math.random()*1800,Math.random()*1200,30,12,Math.random()>.5?0x68818c:0x9a5362,.72);o.setDepth(8);this.traffic.push({o,vx:horizontal?(Math.random()>.5?1:-1)*(40+Math.random()*70):0,vy:horizontal?0:(Math.random()>.5?1:-1)*(40+Math.random()*70)})}}
 makeUI(){this.hud=this.add.text(18,18,'',{fontSize:14,color:'#d9f1f7',lineSpacing:5,backgroundColor:'#07161fdd',padding:12}).setScrollFactor(0).setDepth(100);this.panel=this.add.text(this.scale.width-18,18,'',{fontSize:14,color:'#d9f1f7',align:'right',backgroundColor:'#07161fdd',padding:12}).setOrigin(1,0).setScrollFactor(0).setDepth(100);this.toast=this.add.text(this.scale.width/2,this.scale.height-70,'',{fontSize:16,color:'#e9fbff',backgroundColor:'#09202bdd',padding:{left:16,right:16,top:10,bottom:10}}).setOrigin(.5).setScrollFactor(0).setDepth(110);this.mini=this.add.graphics().setScrollFactor(0).setDepth(100);this.overlay=this.add.rectangle(this.scale.width/2,this.scale.height/2,this.scale.width,this.scale.height,0x061018,.72).setScrollFactor(0).setDepth(150).setVisible(false)}
 newToast(s:string){this.toast.setText(s).setAlpha(1);this.tweens.add({targets:this.toast,alpha:0,delay:1700,duration:500})}
 interact(){if(this.current){if(dist(this.p,this.current)<130){if(this.current.step===0){this.current.step=1;const target=D[this.current.to];this.current.x=target.x+(Math.random()-.5)*120;this.current.y=target.y+(Math.random()-.5)*90;this.newToast(`${t('deliver')} • ${t(D[this.current.to].name)}`)}else if(this.current.kind==='multi'&&this.current.step===1){this.current.step=2;const target=D[this.current.multiTo===undefined?((this.current.to+2)%D.length):this.current.multiTo];this.current.x=target.x;this.current.y=target.y;this.newToast(`${t('deliver')} • ${t(target.name)}`)}else this.complete()}return}
 let best:Job|undefined;let bd=145;for(const j of this.jobs){if(j.active)continue;const dd=dist(this.p,j);if(dd<bd){best=j;bd=dd}}if(best){this.current=best;best.active=true;this.panel.setText(`${missionName(best.kind)}\n${t(best.cargo)}\n${best.reward} ₽`);this.newToast(t('accept'))}}
 complete(){const j=this.current!;let bonus=1;if(j.kind==='timed')bonus+=Math.max(0,j.deadline/60)*.35;if(j.kind==='fragile')bonus+=.28;if(j.kind==='highrisk')bonus+=.4;if(j.kind==='multi')bonus+=.55;if(save.adBoost){bonus*=1.25;save.adBoost=0}const reward=Math.round(j.reward*bonus*(1+Math.min(save.streak,8)*.05));save.money+=reward;save.rep+=j.kind==='highrisk'?4:2;save.deliveries++;save.streak++;save.best=Math.max(save.best,save.streak);this.checkAchievements();platform.persist();platform.score();this.newToast(`+${reward} ₽  •  REP +${j.kind==='highrisk'?4:2}`);if(save.deliveries%5===0)platform.adFull();if(save.deliveries%5===0&&save.story<3){save.story++;platform.persist();this.story()}this.spawnJob(this.jobs.indexOf(j));this.current=undefined;this.panel.setText('')}
 checkAchievements(){const checks:[string,boolean][]=[['first',save.deliveries>=1],['ten',save.deliveries>=10],['streak',save.best>=5],['rich',save.money>=5000],['rep',save.rep>=50],['fleet',save.unlocked.length>=5],['story',save.story>=3],['night',save.day>=5]];for(const [id,ok] of checks)if(ok&&!save.achievements.includes(id)){save.achievements.push(id);this.newToast(`${t('newAchievement')}: ${t(({first:'achFirst',ten:'achTen',streak:'achStreak',rich:'achRich',rep:'achRep',fleet:'achFleet',story:'achStory',night:'achNight'} as any)[id])}`)}}
 story(){const lines=['story1','story2','story3'];this.showModal(`${t('storyChapter')} ${save.story}\n\n${t(lines[save.story-1])}`,t('next'))}
 showModal(text:string,button:string){this.overlay.setVisible(true);const box=this.add.text(this.scale.width/2,this.scale.height/2-35,text,{fontSize:18,color:'#e5f7fc',align:'center',wordWrap:{width:this.scale.width*.72},backgroundColor:'#0a1e29',padding:30,lineSpacing:8}).setOrigin(.5).setScrollFactor(0).setDepth(151);const b=this.add.text(this.scale.width/2,this.scale.height/2+115,button,{fontSize:16,color:'#62ddff',backgroundColor:'#123644',padding:{left:18,right:18,top:10,bottom:10}}).setOrigin(.5).setInteractive().setScrollFactor(0).setDepth(151);b.once('pointerdown',()=>{box.destroy();b.destroy();this.overlay.setVisible(false)})}
 changeWeather(w:Weather){this.weather=w;this.weatherT=45+Math.random()*50;this.rain=[];if(w==='rain'||w==='storm')for(let i=0;i<120;i++)this.rain.push([Math.random()*this.scale.width,Math.random()*this.scale.height,3+Math.random()*7]);this.newToast(t(({clear:'weatherClear',rain:'weatherRain',fog:'weatherFog',storm:'weatherStorm'} as any)[w]))}
 toggleMap(){this.map=!this.map;if(this.map)this.showModal(`${t('map')}\n\n${D.map(x=>t(x.name)).join('  •  ')}`,t('close'))}
 update(_time:number,dt:number){if(this.overlay.visible)return;const d=dt/1000;this.clock+=d;this.weatherT-=d;this.eventT-=d;if(this.weatherT<0){const ws:Weather[]=['clear','rain','fog','storm'];this.changeWeather(ws[Math.floor(Math.random()*ws.length)])}if(this.eventT<0){this.eventT=45+Math.random()*55;this.newToast(t(['eventAccident','eventCheckpoint','eventClosure','eventLights'][Math.floor(Math.random()*4)]))}
  let dx=(this.keys.d.isDown?1:0)-(this.keys.a.isDown?1:0)+(this.cursor.right.isDown?1:0)-(this.cursor.left.isDown?1:0);let dy=(this.keys.s.isDown?1:0)-(this.keys.w.isDown?1:0)+(this.cursor.down.isDown?1:0)-(this.cursor.up.isDown?1:0);const len=Math.hypot(dx,dy)||1;const boost=this.keys.shift.isDown&&this.energy>3;let speed=v().speed*(1+(save.upgrades.engine||0)*.055)*(boost?1.55:1);if(this.weather==='storm')speed*=.82;if(this.weather==='fog')speed*=.9;if(dx||dy){this.p.x=clamp(this.p.x+dx/len*speed*d,30,1770);this.p.y=clamp(this.p.y+dy/len*speed*d,30,1170);if(boost)this.energy=clamp(this.energy-(28-(save.upgrades.battery||0)*3)*d,0,100);else this.energy=clamp(this.energy+.9*d,0,100)}else this.energy=clamp(this.energy+(1.8+(save.upgrades.battery||0)*.2)*d,0,100);
  this.traffic.forEach(q=>{q.o.x+=q.vx*d;q.o.y+=q.vy*d;if(q.o.x<0||q.o.x>1800)q.vx*=-1;if(q.o.y<0||q.o.y>1200)q.vy*=-1;if(dist(this.p,q.o)<23){this.energy=clamp(this.energy-(22-(save.upgrades.brakes||0)*2)*d,0,100)}});
  if(this.current&&this.current.step>0){this.current.deadline-=d;if(this.current.deadline<=0){this.newToast('TIMEOUT');this.current=undefined;save.streak=0;platform.persist()}}this.drawWeather();this.updateHUD();this.updateMini();if(this.clock>300){this.clock=0;save.day++;platform.persist();this.newToast(`${t('day')} ${save.day}`)}}
 drawWeather(){const g=this.add.graphics().setScrollFactor(0).setDepth(90);if(this.weather==='rain'||this.weather==='storm'){g.lineStyle(this.weather==='storm'?2:1,0x8bdcff,this.weather==='storm'?.4:.22);for(const r of this.rain)g.lineBetween(r[0],r[1],r[0]-3,r[1]+r[2]*5)}if(this.weather==='fog'){g.fillStyle(0xb7dbe3,.08);g.fillRect(0,0,this.scale.width,this.scale.height)}this.time.delayedCall(16,()=>g.destroy())}
 updateHUD(){const mins=Math.floor(this.clock/60),secs=Math.floor(this.clock%60).toString().padStart(2,'0');this.hud.setText(`${t('day')} ${save.day}  •  23:${secs}\n${t('money')}: ${save.money} ₽   ${t('rep')}: ${save.rep}\n${t('energy')}: ${Math.round(this.energy)}%   ${t('deliveries')}: ${save.deliveries}`);this.panel.setText(this.current?`${missionName(this.current.kind)}\n${t(this.current.cargo)}\n${this.current.reward} ₽\n${Math.ceil(this.current.deadline)}s`:`${t('weather')}: ${t(({clear:'weatherClear',rain:'weatherRain',fog:'weatherFog',storm:'weatherStorm'} as any)[this.weather])}\n${t('speed')}: ${Math.round(v().speed)}`)}
 updateMini(){this.mini.clear();const x=this.scale.width-170,y=this.scale.height-120,w=145,h=92;this.mini.fillStyle(0x07161f,.9);this.mini.fillRect(x,y,w,h);this.mini.lineStyle(1,0x3c6877,.8);this.mini.strokeRect(x,y,w,h);this.mini.fillStyle(0x5de0ff,1);this.mini.fillCircle(x+this.p.x/1800*w,y+this.p.y/1200*h,3);this.jobs.forEach(j=>{this.mini.fillStyle(j===this.current?0xffd36b:0x4d9aaf,.8);this.mini.fillCircle(x+j.x/1800*w,y+j.y/1200*h,2)})}
}

const config:Phaser.Types.Core.GameConfig={type:Phaser.AUTO,parent:'game',backgroundColor:'#061017',scale:{mode:Phaser.Scale.RESIZE,width:1280,height:720},render:{antialias:true,powerPreference:'high-performance'},scene:[Boot,Menu,Settings,Garage,City]};
new Phaser.Game(config);
