import Phaser from 'phaser';
import './style.css';

type Save={money:number;rep:number;streak:number;vehicle:number;upgrades:{engine:number;brakes:number;battery:number};best:number};
const KEY='last-courier-save-v2';
const loadSave=():Save=>{try{return {...{money:350,rep:0,streak:0,vehicle:0,upgrades:{engine:0,brakes:0,battery:0},best:0},...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {money:350,rep:0,streak:0,vehicle:0,upgrades:{engine:0,brakes:0,battery:0},best:0}}};
const save=(s:Save)=>localStorage.setItem(KEY,JSON.stringify(s));

class SDKBridge{ysdk:any; async init(){try{const y=(window as any).YaGames;if(!y)return;this.ysdk=await y.init();}catch{}} async cloud(s:Save){try{await this.ysdk?.getPlayer?.({scopes:false}).then((p:any)=>p?.setData?.(s,true))}catch{}} ad(){try{this.ysdk?.adv?.showFullscreenAdv?.({callbacks:{}})}catch{}} reward(cb:()=>void){try{this.ysdk?.adv?.showRewardedVideo?.({callbacks:{onRewarded:cb}})}catch{cb()}}}
const sdk=new SDKBridge();

class Boot extends Phaser.Scene{constructor(){super('Boot')}create(){this.add.text(32,32,'ПОСЛЕДНИЙ КУРЬЕР',{fontFamily:'Arial',fontSize:'28px',color:'#e8f1ff'});this.scene.start('City')}}

interface Job{x:number;y:number;reward:number;deadline:number;district:string;kind:string;active:boolean}
class City extends Phaser.Scene{
 save=loadSave(); player!:Phaser.Physics.Arcade.Sprite; cursors!:Phaser.Types.Input.Keyboard.CursorKeys; keys!:any; jobs:Job[]=[]; jobG!:Phaser.GameObjects.Graphics; ui!:Phaser.GameObjects.Text; info!:Phaser.GameObjects.Text; money!:Phaser.GameObjects.Text; pulse=0; fuel=100; time=0; speed=0; current?:Job; traffic:Phaser.GameObjects.Rectangle[]=[];
 constructor(){super('City')}
 create(){
  this.cameras.main.setBackgroundColor('#071018'); this.physics.world.setBounds(0,0,1800,1100);
  this.makeWorld(); this.makePlayer(); this.makeJobs(); this.makeUI(); this.cursors=this.input.keyboard!.createCursorKeys(); this.keys=this.input.keyboard!.addKeys('W,A,S,D,SHIFT,E,ESC');
  this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.x>this.scale.width-250&&p.y>this.scale.height-150)this.acceptNearest()});
  sdk.init();
 }
 makeWorld(){const g=this.add.graphics();g.fillStyle(0x0b151e);g.fillRect(0,0,1800,1100);for(let x=80;x<1750;x+=170){g.fillStyle(0x16242d);g.fillRect(x,0,76,1100);g.fillStyle(0x263943);for(let y=20;y<1080;y+=55)g.fillRect(x+36,y,4,24)}for(let y=70;y<1060;y+=190){g.fillStyle(0x17262f);g.fillRect(0,y,1800,82);g.fillStyle(0x2b3c45);for(let x=15;x<1780;x+=62)g.fillRect(x,y+39,30,4)}for(let i=0;i<30;i++){const x=40+Math.random()*1720,y=40+Math.random()*1020;g.fillStyle(0x18352c);g.fillCircle(x,y,8+Math.random()*12)}this.add.text(100,100,'ЦЕНТР',{fontSize:'24px',color:'#527080'});this.add.text(800,280,'СТАРЫЙ ГОРОД',{fontSize:'24px',color:'#527080'});this.add.text(1280,780,'ПРОМЗОНА',{fontSize:'24px',color:'#527080'});for(let i=0;i<14;i++){const r=this.add.rectangle(Math.random()*1750,Math.random()*1050,28,14,0x516b76);this.traffic.push(r)}}
 makePlayer(){this.player=this.physics.add.sprite(350,500,undefined as any);this.player.setDisplaySize(34,20);this.player.setTint(0x46d9ff);const body=this.add.rectangle(350,500,34,20,0x46d9ff);body.setStrokeStyle(2,0xb9f4ff);this.player.setVisible(false);(this.player as any).bodySprite=body;this.player.setCollideWorldBounds(true);this.cameras.main.startFollow(this.player,true,.08,.08);this.cameras.main.setBounds(0,0,1800,1100)}
 makeJobs(){this.jobG=this.add.graphics();const names=['Экспресс','Аптека','Анонимная посылка','Запчасти','Курьер №17'];for(let i=0;i<7;i++){const x=130+Math.random()*1500,y=120+Math.random()*850;this.jobs.push({x,y,reward:70+Math.floor(Math.random()*140),deadline:35+Math.random()*35,district:i%2?'Старый город':'Центр',kind:names[i%names.length],active:false})}}
 makeUI(){this.ui=this.add.text(22,20,'',{fontSize:'18px',color:'#e8f1ff',lineSpacing:7}).setScrollFactor(0).setDepth(20);this.info=this.add.text(22,108,'',{fontSize:'17px',color:'#9fb4c5',lineSpacing:6}).setScrollFactor(0).setDepth(20);this.money=this.add.text(this.scale.width-230,22,'',{fontSize:'21px',color:'#ffd66b'}).setScrollFactor(0).setDepth(20);this.add.text(this.scale.width-230,70,'ЗАКАЗЫ  [E]',{fontSize:'15px',color:'#66d7ff'}).setScrollFactor(0).setDepth(20)}
 acceptNearest(){let best:Job|undefined,dist=Infinity;for(const j of this.jobs){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,j.x,j.y);if(d<dist&&d<180){dist=d;best=j}}if(best&&!this.current){this.current=best;best.active=true;this.info.setText(`ЗАКАЗ: ${best.kind}\n${best.district} • ${Math.round(best.reward)} ₽\nДоставьте вовремя`);this.save.rep+=1}}
 update(_t:number,dt:number){this.time+=dt/1000;this.pulse+=dt/1000;const k=this.keys;let dx=0,dy=0;if(this.cursors.left.isDown||k.A.isDown)dx--;if(this.cursors.right.isDown||k.D.isDown)dx++;if(this.cursors.up.isDown||k.W.isDown)dy--;if(this.cursors.down.isDown||k.S.isDown)dy++;const boost=k.SHIFT.isDown&&this.fuel>0;const base=145+this.save.upgrades.engine*24;const sp=base*(boost?1.75:1);if(dx||dy){const v=new Phaser.Math.Vector2(dx,dy).normalize().scale(sp);this.player.setVelocity(v.x,v.y);this.speed=sp;if(boost)this.fuel=Math.max(0,this.fuel-dt*0.025)}else{this.player.setVelocity(0);this.speed=0;this.fuel=Math.min(100,this.fuel+dt*0.01)}if(k.E.isDown&&this.time>this.pulse+.3)this.acceptNearest();this.pulse=this.time;const b=(this.player as any).bodySprite;b.setPosition(this.player.x,this.player.y);b.rotation=this.player.body!.velocity.angle();this.updateTraffic(dt);this.updateJobs(dt);this.ui.setText(`НОВОГРАД  •  ${this.clock()}\nСкорость ${Math.round(this.speed)}  |  Батарея ${Math.round(this.fuel)}%\nРепутация ${this.save.rep}  |  Серия ${this.save.streak}`);this.money.setText(`${this.save.money} ₽`);this.drawJobs()}
 updateTraffic(dt:number){for(const r of this.traffic){r.x+=dt*0.025;if(r.x>1810)r.x=-10}}
 updateJobs(dt:number){if(this.current){this.current.deadline-=dt/1000;if(this.current.deadline<=0){this.current.active=false;this.current=undefined;this.save.streak=0;this.info.setText('ЗАКАЗ ПРОСРОЧЕН\nРепутация не пострадала.');sdk.ad();return}const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.current.x,this.current.y);if(d<42){this.save.money+=this.current.reward;this.save.rep+=3;this.save.streak++;this.save.best=Math.max(this.save.best,this.save.streak);this.info.setText(`ДОСТАВЛЕНО ✓\n+${this.current.reward} ₽  •  серия x${this.save.streak}`);this.current.active=false;this.current=undefined;save(this.save);sdk.cloud(this.save)}}}
 drawJobs(){this.jobG.clear();for(const j of this.jobs){if(j.active||this.current===j){this.jobG.lineStyle(2,0x4ddcff,0.8);this.jobG.strokeCircle(j.x,j.y,18);this.jobG.fillStyle(0x4ddcff,0.18);this.jobG.fillCircle(j.x,j.y,30)}else{this.jobG.fillStyle(0xffc857,0.8);this.jobG.fillCircle(j.x,j.y,5)}}if(this.current){this.jobG.lineStyle(3,0x66e6ff,0.45);this.jobG.lineBetween(this.player.x,this.player.y,this.current.x,this.current.y)}}
 clock(){const h=19+Math.floor(this.time/60)%6,m=Math.floor(this.time)%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
}

new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#071018',physics:{default:'arcade',arcade:{gravity:{x:0,y:0},debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[Boot,City],render:{antialias:true,pixelArt:false}});
